-- Course table data
 id |            title            |                            description                            |     instructor     | associatedWorkshop | coverImage | maxStudents | enrolledStudents | totalWeeks | totalModules | status |         createdAt          |         updatedAt          
----+-----------------------------+-------------------------------------------------------------------+--------------------+--------------------+------------+-------------+------------------+------------+--------------+--------+----------------------------+----------------------------
  1 | Test Course                 | Test Description                                                  | Akanksha           |                    |            |          20 |                0 |          0 |            0 | ACTIVE | 2025-05-03 03:30:06.068458 | 2025-05-03 03:30:06.068458
  2 | Introduction to Programming | Fundamentals of programming concepts and logic                   +| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.355163 | 2025-05-03 04:19:05.355163
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/introduction-to-programming  |                    |                    |            |             |                  |            |              |        |                            | 
  3 | Data Structures             | Understanding various data structures and their applications     +| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.356925 | 2025-05-03 04:19:05.356925
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/data-structures              |                    |                    |            |             |                  |            |              |        |                            | 
  4 | Algorithms                  | Essential algorithms and problem-solving techniques              +| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.358329 | 2025-05-03 04:19:05.358329
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/algorithms                   |                    |                    |            |             |                  |            |              |        |                            | 
  5 | Object-Oriented Programming | OOP principles and design patterns                               +| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.359663 | 2025-05-03 04:19:05.359663
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/object-oriented-programming  |                    |                    |            |             |                  |            |              |        |                            | 
  6 | Web Development Basics      | Introduction to HTML, CSS, and JavaScript                        +| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.361285 | 2025-05-03 04:19:05.361285
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/web-development-basics       |                    |                    |            |             |                  |            |              |        |                            | 
  7 | Backend Development         | Server-side programming and database management                  +| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.362954 | 2025-05-03 04:19:05.362954
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/backend-development          |                    |                    |            |             |                  |            |              |        |                            | 
  8 | Frontend Frameworks         | Modern frontend frameworks like React, Angular, or Vue           +| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.364495 | 2025-05-03 04:19:05.364495
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/frontend-frameworks          |                    |                    |            |             |                  |            |              |        |                            | 
  9 | Mobile App Development      | Building mobile applications for iOS and Android                 +| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.366004 | 2025-05-03 04:19:05.366004
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/mobile-app-development       |                    |                    |            |             |                  |            |              |        |                            | 
 10 | DevOps and Deployment       | Continuous integration, delivery, and deployment practices       +| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.367595 | 2025-05-03 04:19:05.367595
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/devops-and-deployment        |                    |                    |            |             |                  |            |              |        |                            | 
 11 | Advanced Topics             | Machine learning, blockchain, and other cutting-edge technologies+| Pratik Khanapurkar | 2                  |            |          25 |                0 |          4 |           12 | ACTIVE | 2025-05-03 04:19:05.368843 | 2025-05-03 04:19:05.368843
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Schedule:                                                        +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 6, 2024 at 9:00 AM                                 +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 8, 2024 at 9:00 AM                              +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 10, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 13, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 15, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 17, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 20, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 22, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 24, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Monday, May 27, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Wednesday, May 29, 2024 at 9:00 AM                             +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | - Friday, May 31, 2024 at 9:00 AM                                +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             |                                                                  +|                    |                    |            |             |                  |            |              |        |                            | 
    |                             | Jitsi Meet Link: https://meet.jit.si/advanced-topics              |                    |                    |            |             |                  |            |              |        |                            | 
(11 rows)

